packages:
  - packages/*

catalog:
  "@moonlight-mod/lunast": ^1.0.1
  "@moonlight-mod/mappings": ^1.1.49
  "@moonlight-mod/moonmap": ^1.0.7
  "@zenfs/core": ^2.0.0
  "@zenfs/dom": ^1.1.3
  microdiff: ^1.5.0
  nanotar: ^0.1.1

catalogs:
  build:
    esbuild: ^0.19.3
    typescript: ^5.3.3
  dev:
    "@moonlight-mod/eslint-config": github:moonlight-mod/eslint-config
    eslint: ^9.39.2
    husky: ^8.0.3
    prettier: ^3.8.1
    taze: ^19.9.2
  types:
    "@types/chrome": ^0.0.313
    "@types/node": 22.14.0
    "@types/react": ^19.0.0
    csstype: ^3.1.3
    standalone-electron-types: ^1.0.0

engineStrict: true

onlyBuiltDependencies:
  - esbuild

packageManagerStrict: true

registry: https://registry.npmjs.org/

strictDepBuilds: true

strictSsl: true
