packages:
  - packages/*

catalogs:
  dev:
    '@moonlight-mod/eslint-config': github:moonlight-mod/eslint-config
    '@types/chrome': ^0.0.313
    '@types/node': ^22.14.0
    esbuild: ^0.19.3
    esbuild-copy-static-files: ^0.1.0
    eslint: ^9.12.0
    husky: ^8.0.3
    prettier: ^3.1.0
    taze: ^19.0.4
    typescript: ^5.3.3
  prod:
    '@moonlight-mod/lunast': ^1.0.1
    '@moonlight-mod/mappings': ^1.1.47
    '@moonlight-mod/moonmap': ^1.0.7
    '@zenfs/core': ^2.0.0
    '@zenfs/dom': ^1.1.3
    microdiff: ^1.5.0
    nanotar: ^0.1.1

engineStrict: true

onlyBuiltDependencies:
  - esbuild

packageManagerStrict: true

registry: https://registry.npmjs.org/

strictDepBuilds: true

strictSsl: true
