packages:
  - packages/*

catalogs:
  dev:
    esbuild: ^0.19.3
    "@types/node": ^22.14.0
    "@flowr/eslint": ^6.0.0
    eslint: ^9.20.0
    husky: ^8.0.3
    prettier: ^3.1.0
    tsx: ^4.19.3
    typescript: ^5.3.3
    "@eslint-react/eslint-plugin": ^1.40.2
    eslint-plugin-react-hooks: ^5.2.0
    taze: ^19.0.4
  prod:
    "@moonlight-mod/lunast": ^1.0.1
    "@moonlight-mod/mappings": ^1.1.21
    "@moonlight-mod/moonmap": ^1.0.5
    "@types/react": ^18.3.10
    csstype: ^3.1.2
    standalone-electron-types: ^1.0.0
    microdiff: ^1.5.0
    nanotar: ^0.1.1
    "@zenfs/core": ^1.8.8
    "@zenfs/dom": ^1.1.3

onlyBuiltDependencies:
  - esbuild

engineStrict: true
strictSsl: true
strictDepBuilds: true
packageManagerStrict: true
