packages:
  - packages/*

catalog:
  "@moonlight-mod/lunast": ^1.0.1
  "@moonlight-mod/moonmap": ^1.0.7
  "@zenfs/core": ^2.0.0
  "@zenfs/dom": ^1.1.3
  microdiff: ^1.5.0
  nanotar: ^0.1.1

catalogs:
  build:
    esbuild: ^0.19.3
    typescript: ^5.3.3
  lint:
    "@biomejs/biome": 2.4.4
    husky: ^8.0.3
  types:
    "@types/chroma-js": ^3.1.0
    "@types/chrome": ^0.0.313
    "@types/flux": ^3.1.14
    "@types/highlightjs": ^9.12.6
    "@types/lodash": ^4.17.14
    "@types/node": 22.14.0
    "@types/platform": ^1.3.6
    "@types/react": ^19.0.0
    csstype: ^3.1.3
    standalone-electron-types: ^1.0.0
    zustand: ^5.0.3

engineStrict: true

onlyBuiltDependencies:
  - esbuild

packageManagerStrict: true

registry: https://registry.npmjs.org/

strictDepBuilds: true

strictSsl: true
