/** biome-ignore-all lint: auto-generated file */

// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "settings.proto" (syntax proto3)
// tslint:disable
import type {
  BinaryReadOptions,
  BinaryWriteOptions,
  IBinaryReader,
  IBinaryWriter,
  PartialMessage
} from "@protobuf-ts/runtime";
import { MessageType, reflectionMergePartial, UnknownFieldHandler, WireType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CustomUserSettings
 */
export interface CustomUserSettings {
  /**
   * @generated from protobuf field: optional CustomUserSettings.Versions versions = 1
   */
  versions?: CustomUserSettings_Versions;
  /**
   * @generated from protobuf field: optional CustomUserSettings.ClientSettings settings = 2
   */
  settings?: CustomUserSettings_ClientSettings;
}
/**
 * @generated from protobuf message CustomUserSettings.Versions
 */
export interface CustomUserSettings_Versions {
  /**
   * @generated from protobuf field: uint32 client_version = 1
   */
  clientVersion: number;
  /**
   * @generated from protobuf field: uint32 server_version = 2
   */
  serverVersion: number;
  /**
   * @generated from protobuf field: uint32 data_version = 3
   */
  dataVersion: number;
}
/**
 * @generated from protobuf message CustomUserSettings.SettingsEntry
 */
export interface CustomUserSettings_SettingsEntry {
  /**
   * @generated from protobuf field: bytes data = 1
   */
  data: Uint8Array;
}
/**
 * @generated from protobuf message CustomUserSettings.MoonlightSettingsEntry
 */
export interface CustomUserSettings_MoonlightSettingsEntry {
  /**
   * @generated from protobuf field: uint32 version = 1
   */
  version: number;
  /**
   * @generated from protobuf field: bytes data = 2
   */
  data: Uint8Array;
}
/**
 * @generated from protobuf message CustomUserSettings.ClientSettings
 */
export interface CustomUserSettings_ClientSettings {
  /**
   * @generated from protobuf field: CustomUserSettings.SettingsEntry shared = 1
   */
  shared?: CustomUserSettings_SettingsEntry;
  /**
   * @generated from protobuf field: CustomUserSettings.MoonlightSettingsEntry moonlight = 14045442
   */
  moonlight?: CustomUserSettings_MoonlightSettingsEntry;
}
// @generated message type with reflection information, may provide speed optimized methods
class CustomUserSettings$Type extends MessageType<CustomUserSettings> {
  constructor() {
    super("CustomUserSettings", [
      { no: 1, name: "versions", kind: "message", T: () => CustomUserSettings_Versions },
      { no: 2, name: "settings", kind: "message", T: () => CustomUserSettings_ClientSettings }
    ]);
  }
  create(value?: PartialMessage<CustomUserSettings>): CustomUserSettings {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined) reflectionMergePartial<CustomUserSettings>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CustomUserSettings
  ): CustomUserSettings {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* optional CustomUserSettings.Versions versions */ 1:
          message.versions = CustomUserSettings_Versions.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.versions
          );
          break;
        case /* optional CustomUserSettings.ClientSettings settings */ 2:
          message.settings = CustomUserSettings_ClientSettings.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.settings
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(message: CustomUserSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
    /* optional CustomUserSettings.Versions versions = 1; */
    if (message.versions)
      CustomUserSettings_Versions.internalBinaryWrite(
        message.versions,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options
      ).join();
    /* optional CustomUserSettings.ClientSettings settings = 2; */
    if (message.settings)
      CustomUserSettings_ClientSettings.internalBinaryWrite(
        message.settings,
        writer.tag(2, WireType.LengthDelimited).fork(),
        options
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CustomUserSettings
 */
export const CustomUserSettings = new CustomUserSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CustomUserSettings_Versions$Type extends MessageType<CustomUserSettings_Versions> {
  constructor() {
    super("CustomUserSettings.Versions", [
      { no: 1, name: "client_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
      { no: 2, name: "server_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
      { no: 3, name: "data_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
    ]);
  }
  create(value?: PartialMessage<CustomUserSettings_Versions>): CustomUserSettings_Versions {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.clientVersion = 0;
    message.serverVersion = 0;
    message.dataVersion = 0;
    if (value !== undefined) reflectionMergePartial<CustomUserSettings_Versions>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CustomUserSettings_Versions
  ): CustomUserSettings_Versions {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* uint32 client_version */ 1:
          message.clientVersion = reader.uint32();
          break;
        case /* uint32 server_version */ 2:
          message.serverVersion = reader.uint32();
          break;
        case /* uint32 data_version */ 3:
          message.dataVersion = reader.uint32();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: CustomUserSettings_Versions,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* uint32 client_version = 1; */
    if (message.clientVersion !== 0) writer.tag(1, WireType.Varint).uint32(message.clientVersion);
    /* uint32 server_version = 2; */
    if (message.serverVersion !== 0) writer.tag(2, WireType.Varint).uint32(message.serverVersion);
    /* uint32 data_version = 3; */
    if (message.dataVersion !== 0) writer.tag(3, WireType.Varint).uint32(message.dataVersion);
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CustomUserSettings.Versions
 */
export const CustomUserSettings_Versions = new CustomUserSettings_Versions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CustomUserSettings_SettingsEntry$Type extends MessageType<CustomUserSettings_SettingsEntry> {
  constructor() {
    super("CustomUserSettings.SettingsEntry", [{ no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }]);
  }
  create(value?: PartialMessage<CustomUserSettings_SettingsEntry>): CustomUserSettings_SettingsEntry {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.data = new Uint8Array(0);
    if (value !== undefined) reflectionMergePartial<CustomUserSettings_SettingsEntry>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CustomUserSettings_SettingsEntry
  ): CustomUserSettings_SettingsEntry {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* bytes data */ 1:
          message.data = reader.bytes();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: CustomUserSettings_SettingsEntry,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* bytes data = 1; */
    if (message.data.length) writer.tag(1, WireType.LengthDelimited).bytes(message.data);
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CustomUserSettings.SettingsEntry
 */
export const CustomUserSettings_SettingsEntry = new CustomUserSettings_SettingsEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CustomUserSettings_MoonlightSettingsEntry$Type extends MessageType<CustomUserSettings_MoonlightSettingsEntry> {
  constructor() {
    super("CustomUserSettings.MoonlightSettingsEntry", [
      { no: 1, name: "version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
      { no: 2, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
    ]);
  }
  create(value?: PartialMessage<CustomUserSettings_MoonlightSettingsEntry>): CustomUserSettings_MoonlightSettingsEntry {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.version = 0;
    message.data = new Uint8Array(0);
    if (value !== undefined) reflectionMergePartial<CustomUserSettings_MoonlightSettingsEntry>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CustomUserSettings_MoonlightSettingsEntry
  ): CustomUserSettings_MoonlightSettingsEntry {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* uint32 version */ 1:
          message.version = reader.uint32();
          break;
        case /* bytes data */ 2:
          message.data = reader.bytes();
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: CustomUserSettings_MoonlightSettingsEntry,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* uint32 version = 1; */
    if (message.version !== 0) writer.tag(1, WireType.Varint).uint32(message.version);
    /* bytes data = 2; */
    if (message.data.length) writer.tag(2, WireType.LengthDelimited).bytes(message.data);
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CustomUserSettings.MoonlightSettingsEntry
 */
export const CustomUserSettings_MoonlightSettingsEntry = new CustomUserSettings_MoonlightSettingsEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CustomUserSettings_ClientSettings$Type extends MessageType<CustomUserSettings_ClientSettings> {
  constructor() {
    super("CustomUserSettings.ClientSettings", [
      { no: 1, name: "shared", kind: "message", T: () => CustomUserSettings_SettingsEntry },
      { no: 14045442, name: "moonlight", kind: "message", T: () => CustomUserSettings_MoonlightSettingsEntry }
    ]);
  }
  create(value?: PartialMessage<CustomUserSettings_ClientSettings>): CustomUserSettings_ClientSettings {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined) reflectionMergePartial<CustomUserSettings_ClientSettings>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CustomUserSettings_ClientSettings
  ): CustomUserSettings_ClientSettings {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* CustomUserSettings.SettingsEntry shared */ 1:
          message.shared = CustomUserSettings_SettingsEntry.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.shared
          );
          break;
        case /* CustomUserSettings.MoonlightSettingsEntry moonlight */ 14045442:
          message.moonlight = CustomUserSettings_MoonlightSettingsEntry.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.moonlight
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
          let d = reader.skip(wireType);
          if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: CustomUserSettings_ClientSettings,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* CustomUserSettings.SettingsEntry shared = 1; */
    if (message.shared)
      CustomUserSettings_SettingsEntry.internalBinaryWrite(
        message.shared,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options
      ).join();
    /* CustomUserSettings.MoonlightSettingsEntry moonlight = 14045442; */
    if (message.moonlight)
      CustomUserSettings_MoonlightSettingsEntry.internalBinaryWrite(
        message.moonlight,
        writer.tag(14045442, WireType.LengthDelimited).fork(),
        options
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message CustomUserSettings.ClientSettings
 */
export const CustomUserSettings_ClientSettings = new CustomUserSettings_ClientSettings$Type();
