// auto-generated
import type ChromaJS from "./mappings/chroma-js";
import type classnames from "./mappings/classnames";
import type DependencyGraph from "./mappings/dependency-graph";
import type ContextMenuActionCreators from "./mappings/discord/actions/ContextMenuActionCreators";
import type UserSettingsModalActionCreators from "./mappings/discord/actions/UserSettingsModalActionCreators";
import type Constants from "./mappings/discord/Constants";
import type AppStartPerformance from "./mappings/discord/common/AppStartPerformance";
import type Alerts from "./mappings/discord/components/common/Alerts";
import type BaseHeaderBar from "./mappings/discord/components/common/BaseHeaderBar";
import type BreadcrumbsCSS from "./mappings/discord/components/common/Breadcrumbs.css";
import type Card from "./mappings/discord/components/common/Card";
import type FileUpload from "./mappings/discord/components/common/FileUpload";
import type HeaderBarCSS from "./mappings/discord/components/common/HeaderBar.css";
import type HelpMessageCSS from "./mappings/discord/components/common/HelpMessage.css";
import type Image from "./mappings/discord/components/common/Image";
import type Components from "./mappings/discord/components/common/index";
import type PanelButton from "./mappings/discord/components/common/PanelButton";
import type ScrollerCSS from "./mappings/discord/components/common/Scroller.css";
import type Select from "./mappings/discord/components/common/Select";
import type ConfirmModal from "./mappings/discord/components/modals/ConfirmModal";
import type DispatcherInstance from "./mappings/discord/Dispatcher";
import type BaseRecord from "./mappings/discord/lib/BaseRecord";
import type Storage from "./mappings/discord/lib/web/Storage";
import type BuildOverrideCSS from "./mappings/discord/modules/build_overrides/web/BuildOverride.css";
import type DiscoveryCSS from "./mappings/discord/modules/discovery/web/Discovery.css";
import type ForumsCSS from "./mappings/discord/modules/forums/web/Forums.css";
import type ForumHeaderCSS from "./mappings/discord/modules/forums/web/Header.css";
import type ForumSortMenuCSS from "./mappings/discord/modules/forums/web/SortMenu.css";
import type ForumTag from "./mappings/discord/modules/forums/web/Tag";
import type GuildSettingsRoleEditCSS from "./mappings/discord/modules/guild_settings/roles/web/GuildSettingsRoleEdit.css";
import type AppCardCSS from "./mappings/discord/modules/guild_settings/web/AppCard.css";
import type AppCardItemCSS from "./mappings/discord/modules/guild_settings/web/AppCardItem.css";
import type GuildSettingsSearchSectionCSS from "./mappings/discord/modules/guild_settings/web/SearchSection.css";
import type CategoryChannelCSS from "./mappings/discord/modules/guild_sidebar/web/CategoryChannel.css";
import type MarkupUtils from "./mappings/discord/modules/markup/MarkupUtils";
import type Menu from "./mappings/discord/modules/menus/web/Menu";
import type MarkupCSS from "./mappings/discord/modules/messages/web/Markup.css";
import type MessageCSS from "./mappings/discord/modules/messages/web/Message.css";
import type Modals from "./mappings/discord/modules/modals/Modals";
import type Oauth2 from "./mappings/discord/modules/oauth2/index";
import type PeoplePageCSS from "./mappings/discord/modules/people/web/PeoplePage.css";
import type SettingsItemConstants from "./mappings/discord/modules/user_settings/redesign/SettingsItemConstants";
import type SettingsItemCreators from "./mappings/discord/modules/user_settings/redesign/SettingsItemCreators";
import type UserSettings from "./mappings/discord/modules/user_settings/UserSettings";
import type Flux from "./mappings/discord/packages/flux";
import type BatchedStoreListener from "./mappings/discord/packages/flux/BatchedStoreListener";
import type ChangeListeners from "./mappings/discord/packages/flux/ChangeListeners";
import type connectStores from "./mappings/discord/packages/flux/connectStores";
import type _Dispatcher from "./mappings/discord/packages/flux/Dispatcher";
import type Emitter from "./mappings/discord/packages/flux/Emitter";
import type LoggingUtils from "./mappings/discord/packages/flux/LoggingUtils";
import type PersistedStore from "./mappings/discord/packages/flux/PersistedStore";
import type Store from "./mappings/discord/packages/flux/Store";
import type UserRecord from "./mappings/discord/records/UserRecord";
import type MarginsCSS from "./mappings/discord/styles/shared/Margins.css";
import type Button from "./mappings/discord/uikit/Button";
import type Flex from "./mappings/discord/uikit/Flex";
import type LegacyButton from "./mappings/discord/uikit/legacy/Button";
import type OverflowTooltip from "./mappings/discord/uikit/OverflowTooltip";
import type TextInput from "./mappings/discord/uikit/TextInput";
import type ClipboardUtils from "./mappings/discord/utils/ClipboardUtils";
import type ComponentDispatchUtils from "./mappings/discord/utils/ComponentDispatchUtils";
import type HTTPUtils from "./mappings/discord/utils/HTTPUtils";
import type MaskedLinkUtils from "./mappings/discord/utils/MaskedLinkUtils";
import type NativeUtils from "./mappings/discord/utils/NativeUtils";
import type HighlightJS from "./mappings/highlight.js";
import type HighlightJSCore from "./mappings/highlight.js/lib/core";
import type lodash from "./mappings/lodash";
import type murmurhash from "./mappings/murmurhash";
import type PlatformJS from "./mappings/platform.js";
import React from "./mappings/react";
import type UUID from "./mappings/uuid/v4";

export type MappedModules = {
  "chroma-js": ChromaJS;
  classnames: classnames;
  "dependency-graph": DependencyGraph;
  "discord/Constants": Constants;
  "discord/Dispatcher": DispatcherInstance;
  "discord/actions/ContextMenuActionCreators": ContextMenuActionCreators;
  "discord/actions/UserSettingsModalActionCreators": UserSettingsModalActionCreators;
  "discord/common/AppStartPerformance": AppStartPerformance;
  "discord/components/common/Alerts": Alerts;
  "discord/components/common/BaseHeaderBar": BaseHeaderBar;
  "discord/components/common/Breadcrumbs.css": BreadcrumbsCSS;
  "discord/components/common/Card": Card;
  "discord/components/common/FileUpload": FileUpload;
  "discord/components/common/HeaderBar.css": HeaderBarCSS;
  "discord/components/common/HelpMessage.css": HelpMessageCSS;
  "discord/components/common/Image": Image;
  "discord/components/common/PanelButton": PanelButton;
  "discord/components/common/Scroller.css": ScrollerCSS;
  "discord/components/common/Select": Select;
  "discord/components/common/index": Components;
  "discord/components/modals/ConfirmModal": ConfirmModal;
  "discord/lib/BaseRecord": BaseRecord;
  "discord/lib/web/Storage": Storage;
  "discord/modules/build_overrides/web/BuildOverride.css": BuildOverrideCSS;
  "discord/modules/discovery/web/Discovery.css": DiscoveryCSS;
  "discord/modules/forums/web/Forums.css": ForumsCSS;
  "discord/modules/forums/web/Header.css": ForumHeaderCSS;
  "discord/modules/forums/web/SortMenu.css": ForumSortMenuCSS;
  "discord/modules/forums/web/Tag": ForumTag;
  "discord/modules/guild_settings/roles/web/GuildSettingsRoleEdit.css": GuildSettingsRoleEditCSS;
  "discord/modules/guild_settings/web/AppCard.css": AppCardCSS;
  "discord/modules/guild_settings/web/AppCardItem.css": AppCardItemCSS;
  "discord/modules/guild_settings/web/SearchSection.css": GuildSettingsSearchSectionCSS;
  "discord/modules/guild_sidebar/web/CategoryChannel.css": CategoryChannelCSS;
  "discord/modules/markup/MarkupUtils": MarkupUtils;
  "discord/modules/menus/web/Menu": Menu;
  "discord/modules/messages/web/Markup.css": MarkupCSS;
  "discord/modules/messages/web/Message.css": MessageCSS;
  "discord/modules/modals/Modals": Modals;
  "discord/modules/oauth2/index": Oauth2;
  "discord/modules/people/web/PeoplePage.css": PeoplePageCSS;
  "discord/modules/user_settings/UserSettings": UserSettings;
  "discord/modules/user_settings/redesign/SettingsItemConstants": SettingsItemConstants;
  "discord/modules/user_settings/redesign/SettingsItemCreators": SettingsItemCreators;
  "discord/packages/flux": Flux;
  "discord/packages/flux/BatchedStoreListener": BatchedStoreListener;
  "discord/packages/flux/ChangeListeners": ChangeListeners;
  "discord/packages/flux/Dispatcher": _Dispatcher;
  "discord/packages/flux/Emitter": Emitter;
  "discord/packages/flux/LoggingUtils": LoggingUtils;
  "discord/packages/flux/PersistedStore": PersistedStore;
  "discord/packages/flux/Store": Store;
  "discord/packages/flux/connectStores": connectStores;
  "discord/records/UserRecord": UserRecord;
  "discord/styles/shared/Margins.css": MarginsCSS;
  "discord/uikit/Button": Button;
  "discord/uikit/Flex": Flex;
  "discord/uikit/OverflowTooltip": OverflowTooltip;
  "discord/uikit/TextInput": TextInput;
  "discord/uikit/legacy/Button": LegacyButton;
  "discord/utils/ClipboardUtils": ClipboardUtils;
  "discord/utils/ComponentDispatchUtils": ComponentDispatchUtils;
  "discord/utils/HTTPUtils": HTTPUtils;
  "discord/utils/MaskedLinkUtils": MaskedLinkUtils;
  "discord/utils/NativeUtils": NativeUtils;
  "highlight.js": HighlightJS;
  "highlight.js/lib/core": HighlightJSCore;
  lodash: lodash;
  murmurhash: murmurhash;
  "platform.js": PlatformJS;
  react: React;
  "uuid/v4": UUID;
};

export declare function WebpackRequire<T extends keyof MappedModules>(module: T): MappedModules[T];
