name: Publish types on npm
on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  types:
    name: Publish types on npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build moonlight
        env:
          NODE_ENV: production
        run: pnpm run build

      - name: Publish types
        run: pnpm publish --filter=./packages/types --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
